language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse unittest2 logutils; fi
    - "pip install -r requirements.txt"
script: nosetests
