sudo: false

language: python

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "LXG1YSvznQX11mLKJkOCoKM+xY12+6RF76ogLZcmxC1ZOezyFeffNXMC9Gr7K5KbspdzazQY1IqD/gFiNWyz6G1tv4IYr4/JD0UTdt6Rc6lgieSQdcjZsLm9kyoSrZt/IHiJ6Bpu7PdB+ezK16ODDu3xlqWb/luksm+2wz+AgF4="
    - secure: "pA84LdauErzPNs3XsY0eSf39LqrqEozo1MrYTplnwJVkNHMfSmLSKuw6qFybXteHo0QbjWvJIKZwreMfyzc8YYc8oBUb6f6snJ4G7fgR5WEmUQOHA2QC3OT10Gcr7qtRv8gD6LQWIbE706TuxpLteMbyc2pU8NJgzgeswkR6j94="

install:
  - pip install awscli
  - pip install -r requires/testing.txt
  - python setup.py develop

script: nosetests

after_success:
  - aws s3 cp .coverage "s3://com-gavinroy-travis/helper/$TRAVIS_BUILD_NUMBER/.coverage.${TRAVIS_PYTHON_VERSION}"

stages:
  - test
  - name: upload_coverage
    if: branch = master
  - name: deploy
    if: tag IS present

jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy3
    - stage: upload coverage
      if: repo = gmr/helper
      python: 3.6
      services: []
      install:
        - pip install awscli coverage codecov
      script:
        - mkdir coverage
        - aws s3 cp --recursive s3://com-gavinroy-travis/helper/$TRAVIS_BUILD_NUMBER/ coverage
        - cd coverage
        - coverage combine
        - cd ..
        - mv coverage/.coverage .
        - coverage report
      after_success: codecov
    - stage: deploy
      if: repo = gmr/helper
      python: 3.6
      install: true
      services: []
      script: true
      after_success: true
      deploy:
        distributions: sdist bdist_wheel
        provider: pypi
        user: crad
        on:
          tags: true
          all_branches: true
        password:
          secure: "RRgrsRDz+8/saBnMewtk1E2NeCFDoLAgmYXVdt1K1+uCH/Wp84I2XbICAMAMLCjCzrgDdbV/B5IUMIfldC9fvBAuVK8W9+kQGbyrDuEWthGHPIVLgcM0EX81x7uYZuDdLguWVbBeOFO5eyEdPOELvdATpt7CmJxQF+bZQD6eZdc="