sudo: false
language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse unittest2 logutils; fi
    - pip install wheel
    - pip install -r requirements.txt
script: nosetests
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 2.7
    tags: true
    all_branches: true
  password:
    secure: "Bh+9GSuZz4IemxdPvwHMDhpuQSTEBwYKESWq5Olk/U+Dvennak038atF5I8XQ/hajxuImpXyBK8rqJDmsdtRr0vik+9wtWrbljK3iUvDJ9OXE7OC8Qxm0HH6hD6pXRae6Qn4bONqqqWuV4NOaPnh2lNHpWJdUZutGdS3r6JREmw="
